# Generated by Django 5.1.2 on 2024-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='copies',
            field=models.IntegerField(choices=[(1, '1 copy'), (2, '2 copies'), (3, '3 copies'), (4, '4 copies'), (5, '5 copies')], default=1),
        ),
    ]
