# Generated by Django 5.1.1 on 2024-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_address', models.TextField()),
                ('correct_address', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
