# Generated by Django 5.1.1 on 2024-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_monthlycopiessummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycopiessummary',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='monthlycopiessummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlycopiessummary',
            name='end_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlycopiessummary',
            name='start_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlycopiessummary',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='monthlycopiessummary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlycopiessummary',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlycopiessummary',
            name='total_copies',
        ),
    ]
