# Generated by Django 5.1.1 on 2024-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_monthlycopiessummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycopiessummary',
            name='total_copies',
            field=models.IntegerField(default=1),
        ),
    ]
