# Generated by Django 5.1.1 on 2024-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCustomers',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('edition', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classifieds',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('edition', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('edition', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('edition', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('edition', models.DateField()),
            ],
        ),
    ]
