# Generated by Django 5.0.4 on 2024-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_address_copies_alter_address_s_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addressrecord',
            name='s_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classified',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expert',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlycopiessummary',
            name='end_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlycopiessummary',
            name='start_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlycopiessummary',
            name='total_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlycopiessummary',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='professional',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
