# Generated by Django 5.1.1 on 2024-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_address_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addressrecord',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
